import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";

const roboto = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Portfilio | Nooshin Bakhtiari",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${roboto.className}`}>{children}</body>
    </html>
  );
}
