import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

// add local font
const recoleta = localfont({
  src: [
    {
      path: "../../public/fonts/RecoletaAlt-Regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-recoleta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Portfilio | Nooshin Bakhtiari",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${recoleta.variable}   ${roboto.className}`}>{children}</body>
    </html>
  );
}
